global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vespa'
    static_configs:
      - targets: ['vespa:19092']  # Vespa metrics endpoint
    metrics_path: '/prometheus/v1/values'
    scheme: http
